package jp.michikusa.chitose.entity;

// Generated 2013/01/06 13:36:34 by Hibernate Tools 4.0.0

/**
 * ItemInfo generated by hbm2java
 */
public class ItemInfo implements java.io.Serializable{
	
	private long id;
	private String category;
	private String name;
	private Integer nitems;
	private Integer buyAmount;
	private Integer sellAmount;
	private String note;
	
	public ItemInfo(){}
	
	public ItemInfo(String category, String name){
		this.category= category;
		this.name= name;
	}
	
	public ItemInfo(String category, String name, Integer nitems, Integer buyAmount,
			Integer sellAmount, String note){
		this.category= category;
		this.name= name;
		this.nitems= nitems;
		this.buyAmount= buyAmount;
		this.sellAmount= sellAmount;
		this.note= note;
	}
	
	public long getId(){
		return this.id;
	}
	
	public void setId(long id){
		this.id= id;
	}
	
	public String getCategory(){
		return this.category;
	}
	
	public void setCategory(String category){
		this.category= category;
	}
	
	public String getName(){
		return this.name;
	}
	
	public void setName(String name){
		this.name= name;
	}
	
	public Integer getNitems(){
		return this.nitems;
	}
	
	public void setNitems(Integer nitems){
		this.nitems= nitems;
	}
	
	public Integer getBuyAmount(){
		return this.buyAmount;
	}
	
	public void setBuyAmount(Integer buyAmount){
		this.buyAmount= buyAmount;
	}
	
	public Integer getSellAmount(){
		return this.sellAmount;
	}
	
	public void setSellAmount(Integer sellAmount){
		this.sellAmount= sellAmount;
	}
	
	public String getNote(){
		return this.note;
	}
	
	public void setNote(String note){
		this.note= note;
	}
	
}
