package jp.michikusa.chitose.entity;
// Generated 2013/01/16 2:06:21 by Hibernate Tools 4.0.0



/**
org.hibernate.tool.hbm2x.pojo.EntityPOJOClass
 * ItemInfo generated by hbm2java
 */
public class ItemInfo  implements java.io.Serializable
 {

    /**
     * テーブルのカラム名を定義
     */
    public static final class Column{
        public static final String id= "id";
        public static final String name= "name";
        public static final String limitNumbers= "limitNumbers";
        public static final String purchasingPrice= "purchasingPrice";
        public static final String sellingPrice= "sellingPrice";
        public static final String note= "note";
        public static final String refCategory= "refCategory";
        private Column(){}
    }



     private long id;
     private String name;
     private Integer limitNumbers;
     private Integer purchasingPrice;
     private Integer sellingPrice;
     private String note;
     private ItemCategory refCategory;


    public ItemInfo() {
    }

	
    public ItemInfo(String name, ItemCategory refCategory) {
        this.name = name;
        this.refCategory = refCategory;
    }

   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getLimitNumbers() {
        return this.limitNumbers;
    }
    
    public void setLimitNumbers(Integer limitNumbers) {
        this.limitNumbers = limitNumbers;
    }
    public Integer getPurchasingPrice() {
        return this.purchasingPrice;
    }
    
    public void setPurchasingPrice(Integer purchasingPrice) {
        this.purchasingPrice = purchasingPrice;
    }
    public Integer getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Integer sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public ItemCategory getRefCategory() {
        return this.refCategory;
    }
    
    public void setRefCategory(ItemCategory refCategory) {
        this.refCategory = refCategory;
    }





}


