package jp.michikusa.chitose.entity;
// Generated 2013/01/16 2:06:21 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
org.hibernate.tool.hbm2x.pojo.EntityPOJOClass
 * ItemCategory generated by hbm2java
 */
public class ItemCategory  implements java.io.Serializable
 {

    /**
     * テーブルのカラム名を定義
     */
    public static final class Column{
        public static final String id= "id";
        public static final String name= "name";
        public static final String itemInfos= "itemInfos";
        private Column(){}
    }



     private long id;
     private String name;
     private Set<ItemInfo> itemInfos = new HashSet<ItemInfo>(0);


    public ItemCategory() {
    }

	
    public ItemCategory(String name) {
        this.name = name;
    }

   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<ItemInfo> getItemInfos() {
        return this.itemInfos;
    }
    
    public void setItemInfos(Set<ItemInfo> itemInfos) {
        this.itemInfos = itemInfos;
    }





}


