package jp.michikusa.chitose.entity;
// Generated 2013/01/15 15:30:15 by Hibernate Tools 4.0.0



/**
org.hibernate.tool.hbm2x.pojo.EntityPOJOClass
 * ItemCategory generated by hbm2java
 */
public class ItemCategory  implements java.io.Serializable
 {


    /**
     * エンティティが対応するテーブルのカラム名定義
     */
    public static final class Column{
        // org.hibernate.type.LongType
        public static final String id= "id";
        // org.hibernate.type.StringType
        public static final String name= "name";

        private Column(){}
    }



     private long id;
     private String name;

    public ItemCategory() {
    }


   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }





}


