package jp.michikusa.chitose.entity;
// Generated 2013/01/15 15:30:15 by Hibernate Tools 4.0.0



/**
org.hibernate.tool.hbm2x.pojo.EntityPOJOClass
 * ItemInfo generated by hbm2java
 */
public class ItemInfo  implements java.io.Serializable
 {


    /**
     * エンティティが対応するテーブルのカラム名定義
     */
    public static final class Column{
        // org.hibernate.type.LongType
        public static final String id= "id";
        // org.hibernate.type.LongType
        public static final String categoryId= "categoryId";
        // org.hibernate.type.StringType
        public static final String name= "name";
        // org.hibernate.type.IntegerType
        public static final String limitNumbers= "limitNumbers";
        // org.hibernate.type.IntegerType
        public static final String purchasingPrice= "purchasingPrice";
        // org.hibernate.type.IntegerType
        public static final String sellingPrice= "sellingPrice";
        // org.hibernate.type.StringType
        public static final String note= "note";
        // org.hibernate.type.ManyToOneType
        public static final String refCategory= "refCategory";

        private Column(){}
    }



     private long id;
     private long categoryId;
     private String name;
     private Integer limitNumbers;
     private Integer purchasingPrice;
     private Integer sellingPrice;
     private String note;
     private ItemCategory refCategory;

    public ItemInfo() {
    }

	
    public ItemInfo(long categoryId, String name, ItemCategory refCategory) {
        this.categoryId = categoryId;
        this.name = name;
        this.refCategory = refCategory;
    }

   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getLimitNumbers() {
        return this.limitNumbers;
    }
    
    public void setLimitNumbers(Integer limitNumbers) {
        this.limitNumbers = limitNumbers;
    }
    public Integer getPurchasingPrice() {
        return this.purchasingPrice;
    }
    
    public void setPurchasingPrice(Integer purchasingPrice) {
        this.purchasingPrice = purchasingPrice;
    }
    public Integer getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Integer sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public ItemCategory getRefCategory() {
        return this.refCategory;
    }
    
    public void setRefCategory(ItemCategory refCategory) {
        this.refCategory = refCategory;
    }





}


