package jp.michikusa.chitose.entity;
// Generated 2013/01/15 7:51:51 by Hibernate Tools 4.0.0



/**
 * ItemCategory generated by hbm2java
 */
public class ItemCategory  implements java.io.Serializable {


     private long id;
     private String category;

    public ItemCategory() {
    }

    public ItemCategory(String category) {
       this.category = category;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


