package jp.michikusa.chitose.entity;

// Generated 2013/01/06 13:36:34 by Hibernate Tools 4.0.0

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable{
	
	private long id;
	private String name;
	private String password;
	
	public User(){}
	
	public User(String name, String password){
		this.name= name;
		this.password= password;
	}
	
	public long getId(){
		return this.id;
	}
	
	public void setId(long id){
		this.id= id;
	}
	
	public String getName(){
		return this.name;
	}
	
	public void setName(String name){
		this.name= name;
	}
	
	public String getPassword(){
		return this.password;
	}
	
	public void setPassword(String password){
		this.password= password;
	}
	
}
